//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PornhubPhotoDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PornhubPhotoDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载“{0}”。 的本地化字符串。
        /// </summary>
        internal static string Msg_Album_Download {
            get {
                return ResourceManager.GetString("Msg.Album.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部完成。 的本地化字符串。
        /// </summary>
        internal static string Msg_AllDone {
            get {
                return ResourceManager.GetString("Msg.AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载相册的所有照片。 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_All {
            get {
                return ResourceManager.GetString("Msg.Help.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示调试信息。 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_Debug {
            get {
                return ResourceManager.GetString("Msg.Help.Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示更多的调试信息。这是“-Debug”的附加选项。 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_DebugInfo {
            get {
                return ResourceManager.GetString("Msg.Help.DebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定下载目录。 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_DownloadDir {
            get {
                return ResourceManager.GetString("Msg.Help.DownloadDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定将下载的照片数量。指定“-All”时选项将被忽略。 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_Length {
            get {
                return ResourceManager.GetString("Msg.Help.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定起始的下载位置（从零开始）。指定“-All”时选项将被忽略。 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_StartIndex {
            get {
                return ResourceManager.GetString("Msg.Help.StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PPD &lt;url&gt; [-All] [-Dir:&lt;path&gt;] [-Index:0] [Length:5] 的本地化字符串。
        /// </summary>
        internal static string Msg_Help_Use {
            get {
                return ResourceManager.GetString("Msg.Help.Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的链接“{0}”。 的本地化字符串。
        /// </summary>
        internal static string Msg_InvalidLink {
            get {
                return ResourceManager.GetString("Msg.InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载“{0}”，第 {1} 个，共 {2} 个。 的本地化字符串。
        /// </summary>
        internal static string Msg_Photo_Download {
            get {
                return ResourceManager.GetString("Msg.Photo.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在重试“{0}”，第 {1} 个，共 {2} 个。第 {3} 次。 的本地化字符串。
        /// </summary>
        internal static string Msg_Photo_Download_Retrying {
            get {
                return ResourceManager.GetString("Msg.Photo.Download.Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成“{0}”，第 {1} 个，共 {2} 个。 的本地化字符串。
        /// </summary>
        internal static string Msg_Photo_DownloadCompleted {
            get {
                return ResourceManager.GetString("Msg.Photo.DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败“{0}”，第 {1} 个，共 {2} 个。 的本地化字符串。
        /// </summary>
        internal static string Msg_Photo_DownloadFailed {
            get {
                return ResourceManager.GetString("Msg.Photo.DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载“{0}”，第 {1} 个，共 {2} 个。 的本地化字符串。
        /// </summary>
        internal static string Msg_Photo_Downloading {
            get {
                return ResourceManager.GetString("Msg.Photo.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pornhub 照片下载 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
